import { t, type Dictionary } from "intlayer";

const propertiesListContent = {
  key: "properties-list",
  content: {
    meta: {
      title: t({
        en: "Browse Properties | SeasideHoliday",
        bg: "Разгледайте имоти | Почивка на морето",
      }),
      description: t({
        en: "Find and book properties near you — apartments, houses, venues and more.",
        bg: "Намерете и резервирайте имоти близо до вас — апартаменти, къщи, обекти и още.",
      }),
    },
    title: t({
      en: "Browse properties",
      bg: "Разгледайте имоти",
    }),
    subtitle: t({
      en: "Find the perfect place for your next stay.",
      bg: "Намерете идеалното място за следващия ви престой.",
    }),
    filters: {
      heading: t({ en: "Filter by:", bg: "Филтрирай по:" }),
      city: {
        label: t({ en: "Destination", bg: "Дестинация" }),
        placeholder: t({ en: "Where are you going?", bg: "Къде отивате?" }),
      },
      keyword: t({
        en: "Search by keywords",
        bg: "Търси по ключови думи",
      }),
      dates: t({ en: "Select dates", bg: "Изберете дати" }),

      price: {
        label: t({ en: "Your budget (per night)", bg: "Бюджет (на нощувка)" }),
        currency: t({ en: "EUR", bg: "EUR" }),
      },
      propertyType: {
        label: t({ en: "Property type", bg: "Тип имот" }),
        hotel: t({ en: "Hotels", bg: "Хотели" }),
        apartment: t({ en: "Apartments", bg: "Апартаменти" }),
        house: t({ en: "Houses", bg: "Къщи" }),
        villa: t({ en: "Villas", bg: "Вили" }),
        hostel: t({ en: "Hostels", bg: "Хостели" }),
        guesthouse: t({ en: "Guest houses", bg: "Къщи за гости" }),
      },
      popularFilters: {
        label: t({ en: "Popular filters", bg: "Популярни филтри" }),
        freeCancellation: t({
          en: "Free cancellation",
          bg: "Безплатно анулиране",
        }),
        breakfastIncluded: t({
          en: "Breakfast included",
          bg: "Закуска включена",
        }),
        pool: t({ en: "Pool", bg: "Басейн" }),
        wifi: t({ en: "Free WiFi", bg: "Безплатен WiFi" }),
        parking: t({ en: "Parking", bg: "Паркинг" }),
        petFriendly: t({ en: "Pet-friendly", bg: "Домашни любимци" }),
        airConditioning: t({ en: "Air conditioning", bg: "Климатик" }),
        kitchen: t({ en: "Kitchen", bg: "Кухня" }),
      },
      rating: {
        label: t({ en: "Guest rating", bg: "Оценка от гости" }),
        above: t({ en: "+", bg: "+" }),
      },
      starRating: {
        label: t({ en: "Star rating", bg: "Брой звезди" }),
        stars: t({ en: "stars", bg: "звезди" }),
      },
      bedrooms: {
        label: t({ en: "Bedrooms", bg: "Спални" }),
      },
      amenities: {
        label: t({ en: "Amenities", bg: "Удобства" }),
        showMore: t({ en: "Show more", bg: "Покажи още" }),
        showLess: t({ en: "Show less", bg: "Покажи по-малко" }),
        categories: {
          views: t({ en: "Views & location", bg: "Изгледи и локация" }),
          kitchen: t({ en: "Kitchen & dining", bg: "Кухня и хранене" }),
          comfort: t({ en: "Comfort", bg: "Комфорт" }),
          outdoors: t({ en: "Outdoors", bg: "На открито" }),
          family: t({ en: "Family", bg: "Семейство" }),
          wellness: t({ en: "Wellness", bg: "Уелнес" }),
          services: t({ en: "Services", bg: "Услуги" }),
          safety: t({
            en: "Safety & accessibility",
            bg: "Безопасност и достъпност",
          }),
        },
        items: {
          sea_view: t({ en: "Sea view", bg: "Изглед към морето" }),
          mountain_view: t({ en: "Mountain view", bg: "Изглед към планина" }),
          lake_view: t({ en: "Lake view", bg: "Изглед към езеро" }),
          beachfront: t({ en: "Beachfront", bg: "На плажа" }),
          ski_to_door: t({ en: "Ski-to-door", bg: "Ски до вратата" }),
          city_center: t({ en: "City center", bg: "Център на града" }),
          kitchen: t({ en: "Kitchen", bg: "Кухня" }),
          kitchenette: t({ en: "Kitchenette", bg: "Кухненски бокс" }),
          coffee_machine: t({ en: "Coffee machine", bg: "Кафемашина" }),
          dishwasher: t({ en: "Dishwasher", bg: "Съдомиялна" }),
          microwave: t({ en: "Microwave", bg: "Микровълнова" }),
          oven: t({ en: "Oven", bg: "Фурна" }),
          restaurant: t({ en: "Restaurant", bg: "Ресторант" }),
          wifi: t({ en: "Free WiFi", bg: "Безплатен WiFi" }),
          air_conditioning: t({ en: "Air conditioning", bg: "Климатик" }),
          heating: t({ en: "Heating", bg: "Отопление" }),
          fireplace: t({ en: "Fireplace", bg: "Камина" }),
          washing_machine: t({ en: "Washing machine", bg: "Пералня" }),
          dryer: t({ en: "Dryer", bg: "Сушилня" }),
          iron: t({ en: "Iron", bg: "Ютия" }),
          tv: t({ en: "TV", bg: "Телевизор" }),
          workspace: t({ en: "Workspace", bg: "Работно място" }),
          pool: t({ en: "Pool", bg: "Басейн" }),
          indoor_pool: t({ en: "Indoor pool", bg: "Закрит басейн" }),
          garden: t({ en: "Garden", bg: "Градина" }),
          bbq: t({ en: "BBQ", bg: "Барбекю" }),
          balcony: t({ en: "Balcony", bg: "Балкон" }),
          terrace: t({ en: "Terrace", bg: "Тераса" }),
          hot_tub: t({ en: "Hot tub", bg: "Джакузи" }),
          pet_friendly: t({ en: "Pet-friendly", bg: "Домашни любимци" }),
          crib: t({ en: "Crib", bg: "Бебешко креватче" }),
          high_chair: t({ en: "High chair", bg: "Столче за хранене" }),
          playground: t({ en: "Playground", bg: "Детска площадка" }),
          board_games: t({ en: "Board games", bg: "Настолни игри" }),
          sauna: t({ en: "Sauna", bg: "Сауна" }),
          spa: t({ en: "Spa", bg: "Спа" }),
          gym: t({ en: "Gym", bg: "Фитнес" }),
          massage: t({ en: "Massage", bg: "Масаж" }),
          reception_24h: t({ en: "24h reception", bg: "Рецепция 24 часа" }),
          breakfast_included: t({
            en: "Breakfast included",
            bg: "Закуска включена",
          }),
          airport_shuttle: t({
            en: "Airport shuttle",
            bg: "Трансфер до летище",
          }),
          ev_charger: t({ en: "EV charger", bg: "Зарядно за електромобил" }),
          luggage_storage: t({
            en: "Luggage storage",
            bg: "Съхранение на багаж",
          }),
          daily_housekeeping: t({
            en: "Daily housekeeping",
            bg: "Ежедневно почистване",
          }),
          ski_storage: t({ en: "Ski storage", bg: "Помещение за ски" }),
          smoke_alarm: t({ en: "Smoke alarm", bg: "Датчик за дим" }),
          fire_extinguisher: t({ en: "Fire extinguisher", bg: "Пожарогасител" }),
          first_aid_kit: t({ en: "First aid kit", bg: "Аптечка" }),
          elevator: t({ en: "Elevator", bg: "Асансьор" }),
          ground_floor: t({ en: "Ground floor", bg: "Партер" }),
          step_free_access: t({
            en: "Step-free access",
            bg: "Достъп без стъпала",
          }),
        },
      },
      clear: t({ en: "Clear all", bg: "Изчисти всички" }),
    },
    results: {
      property: t({ en: "property", bg: "имот" }),
      properties: t({ en: "properties", bg: "имоти" }),
      found: t({ en: "found", bg: "намерени" }),
    },
    sort: {
      label: t({ en: "Sort by", bg: "Подреди по" }),
      recommended: t({ en: "Recommended", bg: "Препоръчани" }),
      price_asc: t({ en: "Price: low to high", bg: "Цена: ниска към висока" }),
      price_desc: t({ en: "Price: high to low", bg: "Цена: висока към ниска" }),
      rating_desc: t({ en: "Top rated", bg: "Най-високо оценени" }),
    },
    showResults: t({ en: "Show results", bg: "Покажи резултати" }),
    empty: {
      title: t({ en: "No properties found", bg: "Няма намерени имоти" }),
      subtitle: t({
        en: "Try adjusting your filters.",
        bg: "Опитайте да промените филтрите.",
      }),
    },
    loadingMore: t({ en: "Loading more...", bg: "Зареждане..." }),
    noMore: t({ en: "No more properties", bg: "Няма повече имоти" }),
    error: t({
      en: "Failed to load properties. Please try again.",
      bg: "Неуспешно зареждане на имоти. Моля, опитайте отново.",
    }),
    card: {
      perNight: t({ en: "/night", bg: "/нощ" }),
      priceFrom: t({ en: "from", bg: "от" }),
      priceOnRequest: t({ en: "Price on request", bg: "Цена при запитване" }),
      night: t({ en: "night", bg: "нощувка" }),
      nights: t({ en: "nights", bg: "нощувки" }),
      seeAvailability: t({ en: "See availability", bg: "Виж наличност" }),
      reviews: t({ en: "reviews", bg: "отзива" }),
      review: t({ en: "review", bg: "отзив" }),
      guests: t({ en: "guests", bg: "гости" }),
      excellent: t({ en: "Excellent", bg: "Отлично" }),
      veryGood: t({ en: "Very good", bg: "Много добро" }),
      good: t({ en: "Good", bg: "Добро" }),
      includedTaxes: t({
        en: "Includes taxes and fees",
        bg: "Включва данъци и такси",
      }),
    },
  },
} satisfies Dictionary;

export default propertiesListContent;
